/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TechniciansRouteImport } from './routes/technicians'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as InstallersRouteImport } from './routes/installers'
import { Route as DataboardRouteImport } from './routes/databoard'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BalancesRouteImport } from './routes/balances'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksDispatchReportAutomationsRouteImport } from './routes/api/public/hooks/dispatch-report-automations'
import { Route as ApiPublicHooksDispatchJobRemindersRouteImport } from './routes/api/public/hooks/dispatch-job-reminders'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TechniciansRoute = TechniciansRouteImport.update({
  id: '/technicians',
  path: '/technicians',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallersRoute = InstallersRouteImport.update({
  id: '/installers',
  path: '/installers',
  getParentRoute: () => rootRouteImport,
} as any)
const DataboardRoute = DataboardRouteImport.update({
  id: '/databoard',
  path: '/databoard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BalancesRoute = BalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchReportAutomationsRoute =
  ApiPublicHooksDispatchReportAutomationsRouteImport.update({
    id: '/api/public/hooks/dispatch-report-automations',
    path: '/api/public/hooks/dispatch-report-automations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchJobRemindersRoute =
  ApiPublicHooksDispatchJobRemindersRouteImport.update({
    id: '/api/public/hooks/dispatch-job-reminders',
    path: '/api/public/hooks/dispatch-job-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balances': typeof BalancesRoute
  '/clients': typeof ClientsRoute
  '/companies': typeof CompaniesRoute
  '/databoard': typeof DataboardRoute
  '/installers': typeof InstallersRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/technicians': typeof TechniciansRoute
  '/upload': typeof UploadRoute
  '/api/public/hooks/dispatch-job-reminders': typeof ApiPublicHooksDispatchJobRemindersRoute
  '/api/public/hooks/dispatch-report-automations': typeof ApiPublicHooksDispatchReportAutomationsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balances': typeof BalancesRoute
  '/clients': typeof ClientsRoute
  '/companies': typeof CompaniesRoute
  '/databoard': typeof DataboardRoute
  '/installers': typeof InstallersRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/technicians': typeof TechniciansRoute
  '/upload': typeof UploadRoute
  '/api/public/hooks/dispatch-job-reminders': typeof ApiPublicHooksDispatchJobRemindersRoute
  '/api/public/hooks/dispatch-report-automations': typeof ApiPublicHooksDispatchReportAutomationsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/balances': typeof BalancesRoute
  '/clients': typeof ClientsRoute
  '/companies': typeof CompaniesRoute
  '/databoard': typeof DataboardRoute
  '/installers': typeof InstallersRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/technicians': typeof TechniciansRoute
  '/upload': typeof UploadRoute
  '/api/public/hooks/dispatch-job-reminders': typeof ApiPublicHooksDispatchJobRemindersRoute
  '/api/public/hooks/dispatch-report-automations': typeof ApiPublicHooksDispatchReportAutomationsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/balances'
    | '/clients'
    | '/companies'
    | '/databoard'
    | '/installers'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/technicians'
    | '/upload'
    | '/api/public/hooks/dispatch-job-reminders'
    | '/api/public/hooks/dispatch-report-automations'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/balances'
    | '/clients'
    | '/companies'
    | '/databoard'
    | '/installers'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/technicians'
    | '/upload'
    | '/api/public/hooks/dispatch-job-reminders'
    | '/api/public/hooks/dispatch-report-automations'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/balances'
    | '/clients'
    | '/companies'
    | '/databoard'
    | '/installers'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/technicians'
    | '/upload'
    | '/api/public/hooks/dispatch-job-reminders'
    | '/api/public/hooks/dispatch-report-automations'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BalancesRoute: typeof BalancesRoute
  ClientsRoute: typeof ClientsRoute
  CompaniesRoute: typeof CompaniesRoute
  DataboardRoute: typeof DataboardRoute
  InstallersRoute: typeof InstallersRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  TechniciansRoute: typeof TechniciansRoute
  UploadRoute: typeof UploadRoute
  ApiPublicHooksDispatchJobRemindersRoute: typeof ApiPublicHooksDispatchJobRemindersRoute
  ApiPublicHooksDispatchReportAutomationsRoute: typeof ApiPublicHooksDispatchReportAutomationsRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technicians': {
      id: '/technicians'
      path: '/technicians'
      fullPath: '/technicians'
      preLoaderRoute: typeof TechniciansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installers': {
      id: '/installers'
      path: '/installers'
      fullPath: '/installers'
      preLoaderRoute: typeof InstallersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/databoard': {
      id: '/databoard'
      path: '/databoard'
      fullPath: '/databoard'
      preLoaderRoute: typeof DataboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balances': {
      id: '/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof BalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-report-automations': {
      id: '/api/public/hooks/dispatch-report-automations'
      path: '/api/public/hooks/dispatch-report-automations'
      fullPath: '/api/public/hooks/dispatch-report-automations'
      preLoaderRoute: typeof ApiPublicHooksDispatchReportAutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-job-reminders': {
      id: '/api/public/hooks/dispatch-job-reminders'
      path: '/api/public/hooks/dispatch-job-reminders'
      fullPath: '/api/public/hooks/dispatch-job-reminders'
      preLoaderRoute: typeof ApiPublicHooksDispatchJobRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BalancesRoute: BalancesRoute,
  ClientsRoute: ClientsRoute,
  CompaniesRoute: CompaniesRoute,
  DataboardRoute: DataboardRoute,
  InstallersRoute: InstallersRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  TechniciansRoute: TechniciansRoute,
  UploadRoute: UploadRoute,
  ApiPublicHooksDispatchJobRemindersRoute:
    ApiPublicHooksDispatchJobRemindersRoute,
  ApiPublicHooksDispatchReportAutomationsRoute:
    ApiPublicHooksDispatchReportAutomationsRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
